Fixed a bug where -g is invoked and OTP gets executed without invoking --otp

diff --git a/ppassdb b/ppassdb
--- a/ppassdb
+++ b/ppassdb
@@ -312,9 +312,7 @@ encryption() {
 		{ [ -n "$multiLineOption" ] && multiLinerText ; } || oneLinerText
 	fi
 	if [ -n "$otpOption" ] ; then
-		validateOtp "$textToEncrypt" && echo "$fileName: OTP URL Validated" 1>&"$outputTo" 
-	else
-		echo "$fileName: OTP URL provided may be invalid" 1>&"$outputTo" 
+		validateOtp "$textToEncrypt" && echo "$fileName: OTP URL Validated" 1>&"$outputTo" || echo "$fileName: OTP URL provided may be invalid" 1>&"$outputTo" 
 	fi
 	# shellcheck disable=SC2086
 	printf "%s" "$textToEncrypt" | $gnupg $1 -o "$inputFile" || exit $?
