Implemented flags and did lots of stuff

diff --git a/ppassdb b/ppassdb
--- a/ppassdb
+++ b/ppassdb
@@ -4,57 +4,65 @@ if [ $# -eq 0 ] ; then
 	echo "Type \"$0 help\" for more"
 else
 	#Checking for adequate dependencies
-	if ! command -v gpg > /dev/null; then echo "gnupg is not installed"; exit 127; fi
+	if ! command -v gpg > /dev/null 2>&1 ; then echo "gnupg is not installed"; exit 127; fi
 	
-	outputOnly(){
-		clear && head -n 1 "$directory"/"$fileName" && echo
+	cleanUp(){
+		[ "$success" -eq 0 ] && rm "$tmpFile"
 	}
 
-	copyToClipboard(){
-		# Clipboards by OS'
-		command -v xclip > /dev/null && clipboard="xclip -selection clip"
-		command -v pbcopy > /dev/null && clipboard="pbcopy"
-		[ -d "/c/Windows" ] && command -v clip.exe > /dev/null && clipboard="clip.exe"
+	showText(){
+		[ "$success" -eq 0 ] && \
+		echo && head -n 1 "$tmpFile" && echo && echo
+	}
 
+	clearClipboard(){
 		[ "$success" -eq 0 ] && [ -n "$clipboard" ] && \
-		head -n 1 "$directory/$fileName" | $clipboard &&\
-		echo Copied to clipboard sucessfully && \
-		rm "$directory/$fileName" && \
 		echo "Clearing the clipboard in 15 seconds" && \
-		sleep 15 && $clipboard < /dev/null && echo &
-
-		# If the script doesn't detect any clipboard programs
-		[ "$success" -eq 0 ] && [ -z "$clipboard" ] && \
-		echo "xclip is not installed" && \
-		trap  'rm "$directory/$fileName" ; exit' INT && \
-		printf "Do you want to read the file here? [y/N]: " && read -r prompt && \
-		[ "$prompt" = y ] || [ "$prompt" = Y ] && outputOnly && \
-		rm "$directory/$fileName"
+		sleep 15 && $clipboard < /dev/null &
 	}
 
 	decryption(){
-		# File name and temporary folder location variables
-		fileName=$(awk 'BEGIN { srand(); print int(rand()*32768) }' /dev/null | md5sum | head -c 32)
-		[ -z "$TEMP" ] && TEMP="/tmp"
-		if [ -w "$TEMP" ]; then directory="$TEMP"
-		elif [ -w "$XDG_CACHE_HOME" ]; then directory="$XDG_CACHE_HOME"
-		elif [ -w "$HOME/.cache"  ]; then directory="$HOME/.cache"
-		elif [ -w "$HOME" ]; then directory="$HOME"
-		elif [ -w "." ]; then directory=.
-		else echo "You don't have any writable directories"; exit 1; fi
+		tmpFile=$(mktemp -u)
 		for lastArg in "$@"; do :; done
 		if [ ! -f "$lastArg" ]; then echo "There is no file input"; exit 1; fi
-		case $2 in
-			toclip) gpg --no-symkey-cache --output "$directory/$fileName" "$lastArg" ; success=$? ; copyToClipboard "$@" ;;
-			toterm) gpg --no-symkey-cache --output "$directory/$fileName" "$lastArg" ; success=$? ; outputOnly ;;
-			*) echo "No option specified for decrytion" && exit 1;;
-		esac
-	}
+		gpg --no-symkey-cache --output "$tmpFile" "$lastArg" ; success=$?
 
-	case "$1" in
+		# Clipboards by OS'
+		command -v xclip > /dev/null 2>&1 && clipboard="xclip -selection clip"
+		command -v pbcopy > /dev/null 2>&1 && clipboard="pbcopy"
+		[ -d "/c/Windows" ] && command -v clip.exe > /dev/null 2>&1 && clipboard="clip.exe"
+
+		[ "$success" -eq 0 ] && [ -n "$clipboard" ] && \
+		head -n 1 "$tmpFile" | $clipboard &&\
+		echo Copied to clipboard sucessfully 
+
+		# If the script doesn't detect any clipboard programs
+		[ "$success" -eq 0 ] && [ -z "$clipboard" ] && \
+		echo "Could not find any clipboards" && \
+		[ -z "$showTextOption" ] && cleanUp "$@" && exit 127
+		$clearClipOption
+		$showTextOption
+	}
+	numOfOperations=0
+	OPTIND=1
+	while getopts ":EDcs" OPTION; do
+		case $OPTION in
+			D) numOfOperations=$((numOfOperations+1)) ; operation=decrypt ;;
+			E) numOfOperations=$((numOfOperations+1)) ; operation=encrypt ;;
+			c) clearClipOption='clearClipboard "$@"' ;;
+			s) showTextOption='showText "$@"' ;;
+			*) echo "-$OPTARG is a unknown option" && exit 1 ;;
+		esac
+	done
+
+	[ $numOfOperations -gt 1 ] && echo "-E and -D options shouldn't be used together " && exit 1
+
+	case "$operation" in
 		decrypt) decryption "$@" ;;
 		encrypt) echo "Work in Progress" ;;
 		help) echo "I'll do the documentation later lol" ;;
 		*) echo "Unknown option was specified" ;;
 	esac
+	
+	cleanUp "$@"
 fi	
