Replaced tabs with 2 spaces

diff --git a/ppassdb b/ppassdb
--- a/ppassdb
+++ b/ppassdb
@@ -49,132 +49,115 @@ $0 -Dc -i \"username\" -n \"website.pass\"
 }
 
 checkDependecies() { 
-	! command -v gpg > /dev/null 2>&1 && 
-	echo "gnupg is not installed" && 
-	exit 127 
+  ! command -v gpg > /dev/null 2>&1 && echo "gnupg is not installed" &&
+  exit 127
 }
 
 searchHome() {
-	if [ -d "/storage/emulated/0/$dirName"  ] ; then
-		{
-		[ -w "/storage/emulated/0" ] && 
-		PPASSDB_HOME="/storage/emulated/0/$dirName" 
-		} ||
-		{
-		echo "You don't have write permissions in Termux" && 
-		exit 1
-		}
-	elif [ -d "$APPDATA/$dirName" ] ; then 
-		PPASSDB_HOME="$APPDATA/$dirName"
-	elif [ -d "$HOME/.$dirName" ] ; then
-		PPASSDB_HOME="$HOME/.$dirName"
-	elif [ -z "$XDG_DATA_HOME" ] && 
-	[ -d "$HOME/.local/share/$dirName" ] ; then
-		PPASSDB_HOME="$HOME/.local/share/$dirName"
-	elif [ -d "$XDG_DATA_HOME/$dirName" ] ; then
-		PPASSDB_HOME="$XDG_DATA_HOME/$dirName"
-	else 
-		defineHome "$@"
-	fi
+  if [ -d "/storage/emulated/0/$dirName"  ] ; then
+    {
+      [ -w "/storage/emulated/0" ] &&
+      PPASSDB_HOME="/storage/emulated/0/$dirName"
+    } || { echo "You don't have write permissions in Termux" && exit 1 ; }
+  elif [ -d "$APPDATA/$dirName" ] ; then PPASSDB_HOME="$APPDATA/$dirName"
+  elif [ -d "$HOME/.$dirName" ] ; then PPASSDB_HOME="$HOME/.$dirName"
+  elif [ -z "$XDG_DATA_HOME" ] && [ -d "$HOME/.local/share/$dirName" ] ; then
+    PPASSDB_HOME="$HOME/.local/share/$dirName"
+  elif [ -d "$XDG_DATA_HOME/$dirName" ] ; then
+    PPASSDB_HOME="$XDG_DATA_HOME/$dirName"
+  else defineHome "$@"
+  fi
 }
 
 defineHome() {
-	if [ -d "/storage/emulated/0" ] ; then
-		{ 
-		[ -w "/storage/emulated/0" ] &&
-		PPASSDB_HOME="/storage/emulated/0/ppassdb"
-		} ||
-		{
-		echo "You don't have write permissions in Termux"
-		exit 1
-		}
-	elif [ -n "$APPDATA" ] && [ -d "/c/Windows" ] ; then 
-		PPASSDB_HOME="$APPDATA"
-	elif [ -n "$XDG_DATA_HOME" ] ; then
-		PPASSDB_HOME="$XDG_DATA_HOME/$dirName"
-	elif [ -z "$XDG_DATA_HOME" ] && [ -d "$HOME/.local/share" ] ; then
-		XDG_DATA_HOME="$HOME/.local/share/$dirName"
-	elif [ -z "$XDG_DATA_HOME" ] && [ ! -d "$HOME/.local/share" ] ; then
-		PPASSDB_HOME="$HOME/.$dirName"
-	else
-		PPASSDB_HOME="$(pwd)/$dirName"
-	fi
-	mkdir -p "$PPASSDB_HOME"
+  if [ -d "/storage/emulated/0" ] ; then 
+    {
+      [ -w "/storage/emulated/0" ] && PPASSDB_HOME="/storage/emulated/0/ppassdb"
+    } ||
+    {
+      echo "You don't have write permissions in Termux"
+      exit 1
+    }
+  elif [ -n "$APPDATA" ] && [ -d "/c/Windows" ] ; then PPASSDB_HOME="$APPDATA"
+  elif [ -n "$XDG_DATA_HOME" ] ; then PPASSDB_HOME="$XDG_DATA_HOME/$dirName"
+  elif [ -z "$XDG_DATA_HOME" ] && [ -d "$HOME/.local/share" ] ; then
+    XDG_DATA_HOME="$HOME/.local/share/$dirName"
+  elif [ -z "$XDG_DATA_HOME" ] && [ ! -d "$HOME/.local/share" ] ; then
+    PPASSDB_HOME="$HOME/.$dirName"
+  else PPASSDB_HOME="$(pwd)/$dirName"
+  fi
+  mkdir -p "$PPASSDB_HOME"
 }
 
 listdb() {
-	cd "$PPASSDB_HOME" || {
-	echo "ppassdb home doesn't exist" && exit 1
-	} 
-	echo "$0 Home Directory: $(pwd)"
-	{
-	[ "$(find ./ | wc -l)" -eq 1 ] && 
-	echo "There are no encrypted files added yet"
-	} ||
-	{ printf "ID's: " && ls -AR ; }
+  cd "$PPASSDB_HOME" || { echo "ppassdb home doesn't exist" && exit 1 ; } 
+  echo "$0 Home Directory: $(pwd)"
+  {
+    [ "$(find ./ | wc -l)" -eq 1 ] && 
+    echo "There are no encrypted files added yet"
+  } || { printf "ID's: " && ls -AR ; }
 }
 
 checkArgs() {
-	[ -n "$iD" ] && iD=$(echo "$iD" | sed "s/^\/*//g")
-	[ -z "$iD" ] && iD="default"
-	[ -z "$fileName" ] && 
-	echo "No name was specified. Please use -n option" && 
-	exit 1
-	fileName=$(echo "$fileName" | sed "s/\//_/g" )
-	inputFile="$PPASSDB_HOME/$iD/$fileName"
-	[ "$operation" = "encrypt" ] && [ ! -d "$iD" ] && 
-	mkdir -p "$PPASSDB_HOME/$iD"
-	[ "$operation" = "decrypt" ] && [ ! -e "$inputFile" ] && {
-	echo "There is no input file" && exit 1
-	}
+  [ -n "$iD" ] && iD=$(echo "$iD" | sed "s/^\/*//g")
+  [ -z "$iD" ] && iD="default"
+  [ -z "$fileName" ] && echo "No name was specified. Please use -n option" && 
+  exit 1
+  fileName=$(echo "$fileName" | sed "s/\//_/g" )
+  inputFile="$PPASSDB_HOME/$iD/$fileName"
+  [ "$operation" = "encrypt" ] && [ ! -d "$iD" ] && 
+  mkdir -p "$PPASSDB_HOME/$iD"
+  [ "$operation" = "decrypt" ] && [ ! -e "$inputFile" ] &&
+  { echo "There is no input file" && exit 1 ; }
 }
 
 #A workaround if the script failed to take care of the clipboard
 #Good Alternative if you don't wanna use the -s option
 makeJavaScript() {
-	escapeText=$(echo "$textToCopy" | sed 's/[\\\"]/\\&/g')
-	javaScriptPath=$(mktemp -u).html
-	fileNameOnly=${javaScriptPath##*/}
-	if [ "$oS" = "Android" ] && [ -w "/storage/emulated/0" ] ; then
-		javaScriptPath="/storage/emulated/0/$fileNameOnly}"
-	elif [ "$oS" = "Android" ] ; then
-		javaScriptPath=""
-		echo "You don't have write permissions in Termux" 
-		[ -z "$showTextOption" ] && { cleanUp "$@" ; exit 1 ; }
-	fi
-	[ -n "$javaScriptPath" ] && { cat << EOF
+  escapeText=$(echo "$textToCopy" | sed 's/[\\\"]/\\&/g')
+  javaScriptPath=$(mktemp -u).html
+  fileNameOnly=${javaScriptPath##*/}
+  if [ "$oS" = "Android" ] && [ -w "/storage/emulated/0" ] ; then
+    javaScriptPath="/storage/emulated/0/$fileNameOnly}"
+  elif [ "$oS" = "Android" ] ; then
+    javaScriptPath=""
+    echo "You don't have write permissions in Termux" 
+    [ -z "$showTextOption" ] && { cleanUp "$@" ; exit 1 ; }
+  fi
+  [ -n "$javaScriptPath" ] && 
+  {
+    cat << EOF
 <html>
-	<head>
-	<title> Copy to system clipboard </title>
-	<script>
-		function copyToClipboard() { 
-			navigator.clipboard.writeText("$escapeText"); 
-		}
-	</script>
+  <head>
+  <title> Copy to system clipboard </title>
+  <script>
+    function copyToClipboard() { 
+      navigator.clipboard.writeText("$escapeText"); 
+    }
+  </script>
 </head>
 <body>
-	<p> Click <button onclick=copyToClipboard()> 
-		Copy </button> to put decrypted text to Clipboard 
-	</p>
+  <p> Click <button onclick=copyToClipboard()> 
+    Copy </button> to put decrypted text to Clipboard 
+  </p>
 </body>
 </html>
 EOF
-	} > "$javaScriptPath"
-	[ -n "$javaScriptPath" ] && {
-	case "$oS" in
-		"Windows") start "$javaScriptPath" ;;
-		"GNU/Linux") command -v xdg-open > /dev/null 2>&1 && 
-		xdg-open "$javaScriptPath" > /dev/null 2>&1 ;;
-		*) command -v open > /dev/null 2>&1 && 
-		open "$javaScriptPath"
-	;;
-	esac
-	echo "Your decrypted file is in file://$javaScriptPath"
-	[ "$oS" = "Android" ] && 
-	echo "It will be in the your Internal Storage"
-	echo "This file will be deleted in $deleteJavaScriptTime seconds"
-	sleep $deleteJavaScriptTime && rm "$javaScriptPath" &
-	}
+  } > "$javaScriptPath"
+  [ -n "$javaScriptPath" ] &&
+  {
+    case "$oS" in
+      "Windows") start "$javaScriptPath" ;;
+      "GNU/Linux") command -v xdg-open > /dev/null 2>&1 && 
+      xdg-open "$javaScriptPath" > /dev/null 2>&1 ;;
+      *) command -v open > /dev/null 2>&1 && open "$javaScriptPath" ;;
+    esac
+    echo "Your decrypted file is in file://$javaScriptPath"
+    [ "$oS" = "Android" ] && 
+    echo "It will be in the your Internal Storage"
+    echo "This file will be deleted in $deleteJavaScriptTime seconds"
+    sleep $deleteJavaScriptTime && rm "$javaScriptPath" &
+  }
 }
 
 cleanUp() { [ -e "$decryptedFile" ] && rm "$decryptedFile" ; }
@@ -182,91 +165,92 @@ cleanUp() { [ -e "$decryptedFile" ] && rm "$decryptedFile" ; }
 showText() { echo &&  echo "$textToCopy" && echo ; }
 
 clearClipboard() {
-	[ -n "$clipboard" ] && {
-	echo "Clearing the clipboard in $clearClipboardTime seconds"
-	sleep $clearClipboardTime && head /dev/null | $clipboard &
-	}
+  [ -n "$clipboard" ] && 
+  {
+    echo "Clearing the clipboard in $clearClipboardTime seconds"
+    sleep $clearClipboardTime && head /dev/null | $clipboard &
+  }
 }
 
 copyToClipboard() {
 # Clipboards by OS'
-	case $oS in
-		"Windows") clipboard="clip.exe" ;;	
-		"Android") command -v "termux-clipboard-set" > \
-			/dev/null 2>&1 && 
-			clipboard="termux-clipboard-set" 
-		;;	
-		"GNU/Linux") 
-			[ -n "$WAYLAND_DISPLAY" ] && 
-			command -v wl-copy > /dev/null 2>&1 && 
-			clipboard="wl-copy" ||
-			command -v xclip > /dev/null 2>&1 && 
-			clipboard="xclip -selection clipboard"
-		;;	
-		*) command -v pbcopy > /dev/null 2>&1 && clipboard="pbcopy"
-		;;	
-	esac
+  case $oS in
+    "Windows") clipboard="clip.exe" ;;  
+    "Android")
+      command -v "termux-clipboard-set" > /dev/null 2>&1 && 
+      clipboard="termux-clipboard-set" 
+    ;;  
+    "GNU/Linux") 
+      {
+        [ -n "$WAYLAND_DISPLAY" ] && 
+        command -v wl-copy > /dev/null 2>&1 &&
+        clipboard="wl-copy"
+      } ||
+      {
+        command -v xclip > /dev/null 2>&1 &&
+        clipboard="xclip -selection clipboard"
+      }
+    ;;  
+    *) command -v pbcopy > /dev/null 2>&1 && clipboard="pbcopy" ;;  
+  esac
 
-	[ -n "$clipboard" ] && {
-	echo "$textToCopy" | tr -d "\n" | $clipboard &&
-	echo "Copied to Clipboard sucessfully"
-	}
+  [ -n "$clipboard" ] &&
+  {
+    echo "$textToCopy" | tr -d "\n" | $clipboard &&
+    echo "Copied to Clipboard sucessfully"
+  }
 
-	$clearClipOption
-	
-	[ -z "$clipboard" ] && echo "Could not find any clipboards" && 
-	[ -z "$showTextOption" ] && 
-	[ -z "$javaScriptOption" ] && { cleanUp "$@" ; exit 127 ; }
+  $clearClipOption
+  
+  [ -z "$clipboard" ] &&
+  echo "Could not find any clipboards" && 
+  [ -z "$showTextOption" ] && 
+  [ -z "$javaScriptOption" ] && { cleanUp "$@" ; exit 127 ; }
 }
 
 generateRandomText() { 
-	textToEncrypt=$(
-	tr -dc "[:alnum:]" < /dev/urandom | fold -w 50 | head -n 1
-	)
+  textToEncrypt=$(tr -dc "[:alnum:]" < /dev/urandom | fold -w 50 | head -n 1)
 }
 
 encryption() {
-	checkDependecies "$@"
-	checkArgs "$@"
-	if [ -n "$generateRandomTextOption" ]; then
-		$generateRandomTextOption
-	else
-		stty -echo
-		printf "Enter text to encrypt: " && read -r textToEncrypt
-		echo
-		printf "Enter the same text again: " && read -r confirmText
-		stty echo
-		echo
-		[ "$textToEncrypt" = "$confirmText" ]  || {
-		echo "Texts do not match" && exit 1
-		}
-	fi
-	echo "$textToEncrypt" | tr -d "\n" |
-	gpg -c --no-symkey-cache --cipher-algo AES256 -o "$inputFile" ||
-	exit 1
-	textToCopy="$textToEncrypt"
-	[ -n "$generateRandomTextOption" ] && [ -z "$javaScriptOption" ] &&
-	copyToClipboard "$@"
-	$javaScriptOption
-	$showTextOption
+  checkDependecies "$@"
+  checkArgs "$@"
+  if [ -n "$generateRandomTextOption" ]; then $generateRandomTextOption
+  else
+    stty -echo
+    printf "Enter text to encrypt: " && read -r textToEncrypt
+    echo
+    printf "Enter the same text again: " && read -r confirmText
+    stty echo
+    echo
+    [ "$textToEncrypt" = "$confirmText" ]  || 
+    { echo "Texts do not match" && exit 1 ; }
+  fi
+  echo "$textToEncrypt" | tr -d "\n" |
+  gpg -c --no-symkey-cache --cipher-algo AES256 -o "$inputFile" || exit 1
+  textToCopy="$textToEncrypt"
+  [ -n "$generateRandomTextOption" ] && [ -z "$javaScriptOption" ] &&
+  copyToClipboard "$@"
+  $javaScriptOption
+  $showTextOption
 }
 
 decryption() {
-	checkDependecies "$@"
-	checkArgs "$@"
-	decryptedFile=$(mktemp -u)
-	gpg --no-symkey-cache -o "$decryptedFile" "$inputFile" || exit 1
-	textToCopy=$(head -n 1 "$decryptedFile")
-	[ -z "$javaScriptOption" ] && copyToClipboard "$@"
-	$javaScriptOption 
-	$showTextOption
-	cleanUp "$@"
+  checkDependecies "$@"
+  checkArgs "$@"
+  decryptedFile=$(mktemp -u)
+  gpg --no-symkey-cache -o "$decryptedFile" "$inputFile" || exit 1
+  textToCopy=$(head -n 1 "$decryptedFile")
+  [ -z "$javaScriptOption" ] && copyToClipboard "$@"
+  $javaScriptOption 
+  $showTextOption
+  cleanUp "$@"
 }
 
 #Start of the script
 [ $# -eq 0 ] && noOperation "$@" && exit
 echo "$*" | sed "s/ /\\n/g" | grep \\--help > /dev/null 2>&1 && help "$@" &&
-exit	
+exit  
 
 [ -z "$PPASSDB_HOME" ] && searchHome "$@"
 
@@ -274,42 +258,35 @@ exit
 { [ -d "/c/Windows" ] && oS="Windows" ; } || 
 {
 case "$(uname)" in
-	*Linux) oS=$(uname -o) ;; 
-	*) oS=$(uname) ;; 
+  *Linux) oS=$(uname -o) ;; 
+  *) oS=$(uname) ;; 
 esac
 }
 
 numOfOperations=0
 OPTIND=1
 while getopts ":hEDLcsji:n:g" OPTION; do
-	case $OPTION in
-		h) help "$@" ; exit ;;
-		D) numOfOperations=$((numOfOperations+1))
-		operation=decrypt
-		;;
-		E) numOfOperations=$((numOfOperations+1))
-		operation=encrypt
-		;;
-		L) numOfOperations=$((numOfOperations+1))
-		operation=list 
-		;;
-		c) clearClipOption='clearClipboard "$@"' ;;
-		s) showTextOption='showText "$@"' ;;
-		j) javaScriptOption='makeJavaScript "$@"' ;;
-		i) iD="$OPTARG" ;;
-		n) fileName="$OPTARG" ;;
-		g) generateRandomTextOption='generateRandomText "$@"' ;;
-		*) unknownOption="1" ; echo "-$OPTARG is an unknown option"
-		;;
-	esac
+  case $OPTION in
+    h) help "$@" ; exit ;;
+    D) numOfOperations=$((numOfOperations+1)) ; operation=decrypt ;;
+    E) numOfOperations=$((numOfOperations+1)) ; operation=encrypt ;;
+    L) numOfOperations=$((numOfOperations+1)) ; operation=list ;;
+    c) clearClipOption='clearClipboard "$@"' ;;
+    s) showTextOption='showText "$@"' ;;
+    j) javaScriptOption='makeJavaScript "$@"' ;;
+    i) iD="$OPTARG" ;;
+    n) fileName="$OPTARG" ;;
+    g) generateRandomTextOption='generateRandomText "$@"' ;;
+    *) unknownOption="1" ; echo "-$OPTARG is an unknown option" ;;
+  esac
 done
 [ -n "$unknownOption" ] && exit 1
 [ $numOfOperations -gt 1 ] && 
 echo "Only one operation can be used at a time" && exit 1
 
 case "$operation" in
-	decrypt) decryption "$@" ;;
-	encrypt) encryption "$@" ;;
-	list) listdb "$@" ;;
-	*) echo "No operation was specified" ; noOperation "$@" ;;
+  decrypt) decryption "$@" ;;
+  encrypt) encryption "$@" ;;
+  list) listdb "$@" ;;
+  *) echo "No operation was specified" ; noOperation "$@" ;;
 esac
